name: release-pr

on:
  push:
    branches: [master]

jobs:
  release-pr:
    name: Maintain Release PR
    uses: p3ol/actions/.github/workflows/release-pr.yml@v1.0.0
    secrets:
      github-token: ${{ secrets.GH_RELEASE_PLEASE_TOKEN_PUBLIC }}
